### ISSUE TITLE
i want to add clevertap_plugin to flutter module for ios as xcframework

### ISSUE THREAD

**Issue by nurhadikusumo** [CleverTap/clevertap-flutter#138]
i want to add clevertap_plugin to flutter module for ios as xcframework.
when i added the module to ios project show error like this, please help 🥲 

> [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method recordEvent on channel clevertap_plugin)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
> <asynchronous suspension>
> #1      CleverTapPlugin.recordEvent (package:clevertap_plugin/clevertap_plugin.dart:386:12)
> <asynchronous suspension>
> 2022-11-28 20:08:25.015331+0700 Kitabisa[58992:9286001] flutter: clevertapEvent clevertapEvent
> 2022-11-28 20:08:25.017297+0700 Kitabisa[58992:9286001] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setDebugLevel on channel clevertap_plugin)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
> <asynchronous suspension>
> #1      CleverTapPlugin.setDebugLevel (package:clevertap_plugin/clevertap_plugin.dart:205:12)
> <asynchronous suspension>
> 2022-11-28 20:08:25.017690+0700 Kitabisa[58992:9286001] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method activate on channel clevertap_plugin)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
> <asynchronous suspension>
> #1      CleverTapPlugin.activate (package:clevertap_plugin/clevertap_plugin.dart:758:12)
> <asynchronous suspension>
> 2022-11-28 20:08:25.017943+0700 Kitabisa[58992:9286001] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method recordEvent on channel clevertap_plugin)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
> <asynchronous suspension>
> #1      CleverTapPlugin.recordEvent (package:clevertap_plugin/clevertap_plugin.dart:386:12)

**Comment by nishant-clevertap** [comment]
Closing this due to inactivity. Feel free to reopen.
