### ISSUE TITLE
App inbox - showInbox method throws error and not opening 

### ISSUE THREAD

**Issue by rajeshzmoke** [CleverTap/clevertap-flutter#159]
I'm using the example code to check the App inbox functionality but its not working

CT plugin 
`clevertap_plugin: ^1.6.0
`
flutter doctor 

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

`app/build.gradle`

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.clevertap.android:clevertap-android-sdk:4.4.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'androidx.core:core:1.3.0'
    implementation 'androidx.fragment:fragment:1.3.6'

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.github.bumptech.glide:glide:4.12.0'

    implementation 'com.android.installreferrer:installreferrer:2.2'
    
    //Optional ExoPlayer Libraries for Audio/Video Inbox Messages. Audio/Video messages will be dropped without these dependencies
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.17.1'
}
```

`build.gradle`

 ```
   dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:perf-plugin:1.4.1'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

Error log output when clicking on `showInbox` 

```
V/CleverTap(29683): Please verify the integration of your app. It is not setup to support Notification Inbox yet.
V/CleverTap(29683): java.lang.IllegalStateException: Current activity reference not found
V/CleverTap(29683): 	at com.clevertap.android.sdk.CleverTapAPI.showAppInbox(CleverTapAPI.java:2623)
V/CleverTap(29683): 	at com.clevertap.clevertap_plugin.CleverTapPlugin.showInbox(CleverTapPlugin.java:1571)
V/CleverTap(29683): 	at com.clevertap.clevertap_plugin.CleverTapPlugin.onMethodCall(CleverTapPlugin.java:469)
V/CleverTap(29683): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
V/CleverTap(29683): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
V/CleverTap(29683): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
V/CleverTap(29683): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
V/CleverTap(29683): 	at android.os.Handler.handleCallback(Handler.java:942)
V/CleverTap(29683): 	at android.os.Handler.dispatchMessage(Handler.java:99)
V/CleverTap(29683): 	at android.os.Looper.loopOnce(Looper.java:201)
V/CleverTap(29683): 	at android.os.Looper.loop(Looper.java:288)
V/CleverTap(29683): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
V/CleverTap(29683): 	at java.lang.reflect.Method.invoke(Native Method)
V/CleverTap(29683): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
V/CleverTap(29683): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by shivamsharma2710** [comment]
Hi @rajeshzmoke 

please confirm if you've added following setup in your `Application` class: 

```
import com.clevertap.android.sdk.ActivityLifecycleCallback;

public class MyApplication extends FlutterApplication {
        @java.lang.Override
        public void onCreate() {
            ActivityLifecycleCallback.register(this); //<--- Must call this before super.onCreate()
            super.onCreate();
        }
    }
```

**Comment by rajeshzmoke** [comment]
@shivamsharma2710  any update?

**Comment by rajeshzmoke** [comment]
this is my full manifest file @shivamsharma2710 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example">
    
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/>


    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />


    <application
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name">
        <!-- Value to be added to enable deferred deep links -->
        <meta-data
            android:name="google_analytics_deferred_deep_link_enabled"
            android:value="true" />

        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <!-- clevertap pushnotification -->
        <service android:name="com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService" 
         android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleInstance"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">

            <!-- unilinks -->
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.link"
                    android:scheme="https" />
            </intent-filter>
            <intent-filter>

            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data
                android:host="hair"
                android:scheme="example" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="hair"
                    android:pathPrefix="/landing/"
                    android:scheme="example" />
            </intent-filter>
            <intent-filter>

            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data
                android:host="skin"
                android:scheme="example" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="skin"
                    android:pathPrefix="/landing/"
                    android:scheme="example" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.com"
                    android:scheme="http" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.com"
                    android:scheme="https" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.in"
                    android:scheme="http" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.in"
                    android:scheme="https" />
            </intent-filter>
        <!-- Branch IO -->
          <intent-filter>
                <!-- If utilizing $deeplink_path please explicitly declare your hosts, or utilize a wildcard(*) -->
                <data android:scheme="skbranch" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            <!-- Branch App Links - Live App -->
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="v3upr.app.link" />
                <!-- example-alternate domain is required for App Links when the Journeys/Web SDK and Deepviews are used inside your website.  -->
                <data android:scheme="https" android:host="v3upr-alternate.app.link" />
            </intent-filter>
           <!-- Branch App Links - Test App -->
           <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="v3upr.test-app.link" />
                <!-- example-alternate domain is required for App Links when the Journeys/Web SDK and Deepviews are used inside your website.  -->
                <data android:scheme="https" android:host="v3upr-alternate.test-app.link" />
            </intent-filter>


        </activity>

         <!-- Branch init -->
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />     <!-- Set to true to use Branch_Test_Key (useful when simulating installs and/or switching between debug and production flavors) -->


        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="CLEVERTAP_ACCOUNT_ID"
            android:value="@string/clevertap_account_id" />
        <meta-data
            android:name="CLEVERTAP_TOKEN"
            android:value="@string/clevertap_account_token" />

        <meta-data
            android:name="CLEVERTAP_BACKGROUND_SYNC"
            android:value="1" />

    </application>
</manifest>

```

**Comment by shivamsharma2710** [comment]
Hi @rajeshzmoke 

Please replace the `${applicationName}` with the name of your application class as follows:

```
<application
        android:name=".MyApplication">
        ......
 </application>
```


There is a possibility, the Flutter Gradle plugin in your project is failed to supply the value of  `${applicationName}` in run time, hence try this change and let me know if this helps.

**Comment by rajeshzmoke** [comment]
> Hi @rajeshzmoke
> 
> Please replace the `${applicationName}` with the name of your application class as follows:
> 
> ```
> <application
>         android:name=".MyApplication">
>         ......
>  </application>
> ```
> 
> There is a possibility, the Flutter Gradle plugin in your project is failed to supply the value of `${applicationName}` in run time, hence try this change and let me know if this helps.

yea this seems to have fixed this issue, thanks

**Comment by heitor598** [comment]
The official documentation does not mention adding `implementation 'com.clevertap.android:clevertap-android-sdk:4.4.0'`.
