### ISSUE TITLE
NullPointerException on CleverTapPlugin - Probably in notification flow

### ISSUE THREAD

**Issue by danilopena** [CleverTap/clevertap-flutter#18]
Our firebase Crashlytics is registering this crash. We upgraded CleverTap, but the error persists.

Somebody can help?

@darshanclevertap have reviewed this issue. Im reopening in the correct repository.

Our version:

In flutter: clevertap_plugin: 1.1.4
Android: implementation 'com.clevertap.android:clevertap-android-sdk:3.8.2'

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
at com.clevertap.clevertap_plugin.CleverTapPlugin.runOnMainThread(CleverTapPlugin.java:1524)
at com.clevertap.clevertap_plugin.CleverTapPlugin.invokeMethodOnUiThread(CleverTapPlugin.java:1540)
at com.clevertap.clevertap_plugin.CleverTapPlugin.beforeShow(CleverTapPlugin.java:1566)
at com.clevertap.android.sdk.CleverTapAPI.displayNotification(CleverTapAPI.java:4070)
at com.clevertap.android.sdk.CleverTapAPI.notificationReady(CleverTapAPI.java:4028)
at com.clevertap.android.sdk.CleverTapAPI$29.run(CleverTapAPI.java:4017)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by darshanclevertap** [comment]
@danilopena Thanks for raising this here, we'll add the fix and release this with the next version soon.

**Comment by darshanclevertap** [comment]
@danilopena Can you upgrade to 1.2.0 and see if this issue exists?
