### ISSUE TITLE
ArrayIndexOutOfBounds - CTCarouselMessageViewHolder crash

### ISSUE THREAD

**Issue by danilopena** [CleverTap/clevertap-flutter#19]
Hey guys our firebase started register this crash.

Some data to help on analysis.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at com.clevertap.android.sdk.CTCarouselMessageViewHolder$CarouselPageChangeListener.onPageSelected(CTCarouselMessageViewHolder.java:147)
       at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
       at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
       at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
       at android.view.View.dispatchTouchEvent(View.java:13471)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2888)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:731)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:689)
       at android.view.View.dispatchPointerEvent(View.java:13719)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6148)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5926)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5428)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5394)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5553)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5402)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5610)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5428)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5394)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5402)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8435)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8368)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8321)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8550)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
<img width="828" alt="Captura de Tela 2020-09-09 às 09 48 02" src="https://user-images.githubusercontent.com/6910678/92600244-ae77a100-f281-11ea-8916-a6d652b305ae.png">

<img width="487" alt="Captura de Tela 2020-09-09 às 09 47 05" src="https://user-images.githubusercontent.com/6910678/92600246-ae77a100-f281-11ea-9878-ccc7a09d827b.png">

<img width="485" alt="Captura de Tela 2020-09-09 às 09 46 57" src="https://user-images.githubusercontent.com/6910678/92600247-ae77a100-f281-11ea-99d9-799d848bfb6c.png">

Best regards!

**Comment by lucaspizzo** [comment]
Hey guys @kumaratulismu @darshanclevertap any news about this issue? I work in the same project with @danilopena and we still experiencing this bug.

**Comment by piyush-kukadiya** [comment]
@lucaspizzo We are looking into it, will keep you posted here once its fixed.

**Comment by darshanclevertap** [comment]
@danilopena Can you upgrade to 1.2.0 and see if this issue exists?
