### ISSUE TITLE
I have got "Logo is null" error every time when device recive a notification 

### ISSUE THREAD

**Issue by lokesh-univest** [CleverTap/clevertap-flutter#243]
I am using clevertap_plugin: ^2.2.0 in my application

I have added following meta tag in android manifest for adding the logo in notification and logo is visible in the notification:

```
 <meta-data
            android:name="CLEVERTAP_NOTIFICATION_ICON"
            android:value="ic_launcher"/>
```

Error:

```
W/System  (10697): A resource failed to call end. 
W/System.err(10697): java.lang.Exception: Logo is null
W/System.err(10697): 	at com.clevertap.android.sdk.Utils.getAppIcon(Utils.java:464)
W/System.err(10697): 	at com.clevertap.android.sdk.Utils.getDownloadedBitmapPostFallbackIconCheck(Utils.java:250)
W/System.err(10697): 	at com.clevertap.android.sdk.bitmap.NotificationBitmapDownloadRequestHandler.handleRequest(NotificationBitmapDownloadRequestHandler.kt:22)
W/System.err(10697): 	at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.handleRequest$lambda$0(BitmapDownloadRequestHandlerWithTimeLimit.kt:31)
W/System.err(10697): 	at com.clevertap.android.sdk.bitmap.BitmapDownloadRequestHandlerWithTimeLimit.lambda$ew2Zy24Br1JCBon4UAsR42b7CBc(Unknown Source:0)
W/System.err(10697): 	at com.clevertap.android.sdk.bitmap.-$$Lambda$BitmapDownloadRequestHandlerWithTimeLimit$ew2Zy24Br1JCBon4UAsR42b7CBc.call(Unknown Source:4)
W/System.err(10697): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err(10697): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/System.err(10697): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/System.err(10697): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by manavk11** [comment]
You can resolve this by adding a a large logo in advance option when creating notification

**Comment by Anush-Shand** [comment]
@manavk11 Thanks for pointing to the fix. Closing this due to inactivity
