### ISSUE TITLE
Null Pointer Exception on Clevertap plugin(2.5.0)

### ISSUE THREAD

**Issue by abhinand-kv** [CleverTap/clevertap-flutter#275]
dependencies:
clevertap_plugin: 2.5.0

PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.clevertap.clevertap_plugin.Utils.mapToBundle(Unknown Source:35)
	at com.clevertap.clevertap_plugin.CleverTapPlugin.pushNotificationClickedEvent(Unknown Source:8)
	at com.clevertap.clevertap_plugin.CleverTapPlugin.onMethodCall(Unknown Source:1576)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:41)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
)

**Comment by Anush-Shand** [comment]
This has been fixed in v3.0.0
