### ISSUE TITLE
showInbox not working on android

### ISSUE THREAD

**Issue by tlworkssoftware** [CleverTap/clevertap-flutter#93]
After updating to the latest version of flutter 2.10.0, I can no longer open the inbox on Android.

`CleverTapPlugin.showInbox(styleConfig);`

Someone with the same problem?

**Comment by william-ct** [comment]
Hey @tlworkssoftware , showInbox functionality works for flutter version 2.10.0 and above. Can you try updating the app to flutter V2.10.1 and check? Also can you post logs when you are clicking showInbox in your app. Thanks!

**Comment by william-ct** [comment]
Hi @tlworkssoftware, Do you have the CleverTap logs enabled? In your Application class can you add  `CleverTapAPI.setDebugLevel(3);` and paste the logs from the downgraded Flutter version app?

**Comment by tlworkssoftware** [comment]
> Hi @tlworkssoftware, Do you have the CleverTap logs enabled? In your Application class can you add `CleverTapAPI.setDebugLevel(3);` and paste the logs from the downgraded Flutter version app?

```
V/CleverTap( 2945): java.lang.IllegalStateException: Current activity reference not found
V/CleverTap( 2945): 	at com.clevertap.android.sdk.n.r1(CleverTapAPI.java:2384)
V/CleverTap( 2945): 	at e.h.a.d.S0(CleverTapPlugin.java:1461)
V/CleverTap( 2945): 	at e.h.a.d.onMethodCall(CleverTapPlugin.java:427)
V/CleverTap( 2945): 	at io.flutter.plugin.common.i$a.a(MethodChannel.java:262)
V/CleverTap( 2945): 	at io.flutter.embedding.engine.f.c.i(DartMessenger.java:296)
V/CleverTap( 2945): 	at io.flutter.embedding.engine.f.c.j(DartMessenger.java:320)
V/CleverTap( 2945): 	at io.flutter.embedding.engine.f.c.k(Unknown Source:0)
V/CleverTap( 2945): 	at io.flutter.embedding.engine.f.a.run(Unknown Source:12)
V/CleverTap( 2945): 	at android.os.Handler.handleCallback(Handler.java:883)
V/CleverTap( 2945): 	at android.os.Handler.dispatchMessage(Handler.java:100)
V/CleverTap( 2945): 	at android.os.Looper.loop(Looper.java:241)
V/CleverTap( 2945): 	at android.app.ActivityThread.main(ActivityThread.java:7617)
V/CleverTap( 2945): 	at java.lang.reflect.Method.invoke(Native Method)
V/CleverTap( 2945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
V/CleverTap( 2945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
V/CleverTap( 2945): PostAsyncSafely Task: queueEvent starting on...pool-30-thread-1
V/CleverTap:69R-57K-485Z( 2945): Local cache doesn't need to be updated
D/CleverTap:69R-57K-485Z( 2945): Queued event: {"evtName":"open_inbox","evtData":{},"s":1645094198,"pg":1,"type":"event","ep":1645094217,"f":false,"lsl":-1028520,"dsync":false}
V/CleverTap:69R-57K-485Z( 2945): Queued event to DB table EVENTS: {"evtName":"open_inbox","evtData":{},"s":1645094198,"pg":1,"type":"event","ep":1645094217,"f":false,"lsl":-1028520,"dsync":false}
D/CleverTap:69R-57K-485Z( 2945): Network retry #0
D/CleverTap:69R-57K-485Z( 2945): Failure count is 0. Setting delay frequency to 1s
V/CleverTap:69R-57K-485Z( 2945): Scheduling delayed queue flush on main event loop
V/CleverTap( 2945): PostAsyncSafely Task: queueEvent executed successfully on...pool-30-thread-1
```

**Comment by tlworkssoftware** [comment]
@william-ct Through the log I managed to understand the reason and solved the problem, it was necessary to declare: `ActivityLifecycleCallback.register(this);`
Thanks for the help.
